api/urls.py
from django.conf.urls import url
from api import views

urlpatterns = [
    url(r'^api/carbon$', views.entry_list),
    url(r'^api/carbon/(?P<pk>[0-9]+)$', views.entry_detail),
    url(r'^api/carbon/scope$', views.categories),
]

cs30_webapp/api/urls.py
from django.conf.urls import url
from api import views
app_name= 'api'

urlpatterns = [
    url(r'^api/carbon$', views.entry_list),
    url(r'^api/carbon/(?P<pk>[0-9]+)$', views.entry_detail),
    url(r'^api/carbon/scope$', views.categories),
    url(r'^api/carbon/info$', views.item_calc),
    url(r'^api/home$', views.home, name='home'),
    url(r'^api/carbon/search/(?P<query>[0-9a-zA-Z .!?*\\-]+)$', views.search),
]

cs30_webapp/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from webapp import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.home, name='home'),
    path('webapp/', include('webapp.urls')),
    path('admin/', admin.site.urls),
    path('register/', views.register, name='register'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout')
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

cs30_webapp/webapp/urls.py
from django.urls import path
from webapp import views
app_name = 'webapp'

urlpatterns = [
    path('', views.home, name='home'),
    path('dbview/', views.dbview, name='dbview'),
    path('register/', views.register, name='register'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('edit/<refnum>', views.edit, name='edit'),
    path('delete/<refnum>', views.delete, name='delete'),
    path('add/', views.add, name='add'),
    path('viewdb/', views.search, name='search'),
]

webapp/urls.py
from django.urls import path
from webapp import views
app_name = 'webapp'

urlpatterns = [
    path('', views.home, name='home'),
    path('dbview/', views.dbview, name='dbview'),
    path('register/', views.register, name='register'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
]

cs30_webapp/webapp/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.user.username

cs30_webapp/webapp/forms.py
from django import forms
from django.contrib.auth.models import User


SCOPE_CHOICES = (("Scope 1", "Scope 1"),
                 ("Scope 2", "Scope 2"),
                 ("Scope 3", "Scope 3"),
                 ("Outside of Scopes", "Outside of Scopes")
                 )

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    def __init__(self, *args, **kwargs):
        super(UserForm, self).__init__(*args, **kwargs)

        for fieldname in ['username']:
            self.fields[fieldname].help_text = None
    class Meta:
        model = User
        fields = ('username', 'email', 'password',)


class EditForm(forms.Form):
    scope = forms.ChoiceField(choices = SCOPE_CHOICES)
    level1 = forms.CharField(max_length = 30, min_length = 1, required=False)
    level2 = forms.CharField(max_length = 30, min_length = 1, required=False)
    level3 = forms.CharField(max_length = 30, min_length = 1, required=False)
    level4 = forms.CharField(max_length = 30, min_length = 1, required=False)
    level5 = forms.CharField(max_length = 30, min_length = 1, required=False)
    ef = forms.FloatField(max_value = 99999, min_value = 0.000001)
    cu = forms.CharField(max_length = 30)
    preference =  forms.IntegerField(min_value = 0, max_value=2)
    source = forms.CharField(max_length = 30)

class UploadForm(forms.Form):
    ref_num = forms.IntegerField(min_value = 0, max_value = 99999)
    scope = forms.ChoiceField(choices = SCOPE_CHOICES)
    level1 = forms.CharField(max_length = 30, min_length = 1)
    level2 = forms.CharField(max_length = 30, min_length = 1, required=False)
    level3 = forms.CharField(max_length = 30, min_length = 1, required=False)
    level4 = forms.CharField(max_length = 30, min_length = 1, required=False)
    level5 = forms.CharField(max_length = 30, min_length = 1, required=False)
    ef = forms.FloatField(max_value = 99999, min_value = 0)
    cu = forms.CharField(max_length = 30)
    preference =  forms.IntegerField(min_value = 0, max_value=2)
    source = forms.CharField(max_length = 30)

webapp/forms.py
from django import forms
from django.contrib.auth.models import User


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    def __init__(self, *args, **kwargs):
        super(UserForm, self).__init__(*args, **kwargs)

        for fieldname in ['username']:
            self.fields[fieldname].help_text = None
    class Meta:
        model = User
        fields = ('username', 'email', 'password',)

cs30_webapp/api/views.py
from django.shortcuts import render
from django.http.response import JsonResponse
from django.http import HttpRequest
from django.db.models import Q
from rest_framework.parsers import JSONParser
from rest_framework import status, generics, filters
from rest_framework.decorators import api_view
from api.models import FlatfileEntry, NavigationInfo, CalculationInfo, OtherInfo
from api.serializers import ApiSerializer, NavigationSerializer, SearchSerializer
import json

def home(request):
    return render(request, 'api/home.html')

@api_view(['GET'])
def search(request, query):
    if request.method == 'GET':
        queryString = query
        try:
            #Int has been passed, check ref_num - NOTE: some issue with search, so an integer search does not function currently
            queryInt = int(queryString)
            entries = FlatfileEntry.objects.filter(Q(ref_num__icontains=queryInt))
            api_serializer = ApiSerializer(entries, many=True)
            return JsonResponse(api_serializer.data, safe=False, status=status.HTTP_200_OK)
        except ValueError:
            #Non int, check text fields
            entries = FlatfileEntry.objects.filter(Q(navigation_info__scope__icontains=queryString) | Q(navigation_info__level1__icontains=queryString) | Q(navigation_info__level2__icontains=queryString) | Q(navigation_info__level3__icontains=queryString) | Q(navigation_info__level4__icontains=queryString) | Q(navigation_info__level5__icontains=queryString) | Q(calculation_info__cu__icontains=queryString) | Q(other_info__source__icontains=queryString))
            api_serializer = ApiSerializer(entries, many=True)
            return JsonResponse(api_serializer.data, safe=False, status=status.HTTP_200_OK)
        except:
            return JsonResponse({}, status=status.HTTP_400_BAD_REQUEST)
    else:
        return JSONResponse({}, status=status.HTTP_400_BAD_REQUEST)

@api_view(['GET','POST','DELETE'])
def entry_list(request):
    #GET list of entries, POST new entry, DELETE all entries
    if request.method == 'GET': #Retreive all entries or find entries by ref_number
        entries = FlatfileEntry.objects.all()

        ref_num = request.GET.get('ref_num', None)
        if ref_num is not None:
            entries = entries.filter(ref_num__icontains=ref_num)

        api_serializer = ApiSerializer(entries, many=True)
        return JsonResponse(api_serializer.data, safe=False, status=status.HTTP_200_OK)
    elif request.method == 'POST': #Create and save new entry
        '''
        NOTE: This is a security issue - there is no restriction one who can input data, allowing
        for malicious actors to tamper with the database
        '''
        entry_data = request.data
        if 'payload' in entry_data.keys():
            entry_data = json.loads(entry_data['payload'])

        #Check if ref num in db, if so, reject, else, serializers
        refNum = entry_data['ref_num']
        print(refNum)
        try:
            e = FlatfileEntry.objects.get(pk=refNum)
            print(e)
            if e != None:
                return JsonResponse({}, status=status.HTTP_409_CONFLICT)
        except:
            pass

        api_serializer = ApiSerializer(data=entry_data)
        if api_serializer.is_valid():
            api_serializer.save()
            return JsonResponse({}, status=status.HTTP_201_CREATED)
        return JsonResponse(api_serializer.errors, status=status.HTTP_400_BAD_REQUEST)
    elif request.method == 'DELETE': #Delete all entries - likely not needed in final implementation
        '''
        NOTE: this is a security issue - the is no restriction on who can send this delete request
        '''
        count = FlatfileEntry.objects.all().delete()
        #delete artifacts from nav, calc and other info
        NavigationInfo.objects.all().delete()
        CalculationInfo.objects.all().delete()
        OtherInfo.objects.all().delete()
        return JsonResponse({'message': '{} entires were deleted'.format(count[0])}, status=status.HTTP_200_OK)


@api_view(['GET','PUT','DELETE'])
def entry_detail(request, pk):
    #find entry by id
    entry = FlatfileEntry
    try:
        entry = FlatfileEntry.objects.get(pk=pk)
    except entry.DoesNotExist:
        return JsonResponse({}, status=status.HTTP_404_NOT_FOUND)
    except:
        return JsonResponse({}, status=status.HTTP_400_BAD_REQUEST)

    #GET / PUT / DELETE entry
    if request.method == 'GET': #Gets entry by specified id
        api_serializer = ApiSerializer(entry)
        return JsonResponse(api_serializer.data, status=status.HTTP_200_OK)
    elif request.method == 'PUT': #Update an existing entry
        '''
        NOTE: this is a security issue - the is no restriction on who can send this update request,
        allowing for malicious actors to tamper with data
        '''
        entry_data = request.data
        if 'payload' in entry_data.keys():
            entry_data = json.loads(entry_data['payload'])

        api_serializer = ApiSerializer(entry, data=entry_data)
        if api_serializer.is_valid():
            api_serializer.save()
            return JsonResponse({}, status=status.HTTP_200_OK)
        return JsonResponse(api_serializer.errors, status=status.HTTP_400_BAD_REQUEST)
    elif request.method == 'DELETE': #Deletes entry by id
        '''
        NOTE: this is a security issue - the is no restriction on who can send this delete request
        '''
        entry.delete()
        return JsonResponse({}, status=status.HTTP_200_OK)

@api_view(['GET','POST'])
def categories(request):
    if request.method == 'GET': #Complete
        #Return a list of scopes
        dict_scope_list = list(NavigationInfo.objects.all().values('scope').distinct())
        scopes = []
        for dict in dict_scope_list:
            scopes.append(dict['scope'])
        return JsonResponse({'message':scopes}, status=status.HTTP_200_OK)
    if request.method == 'POST':
        #Return list of possible levels
        path = request.data
        levels = ['scope','level1','level2','level3','level4','level5']
        for p in path.keys():
            if p not in levels:
                return JsonResponse({'message':'Malformed request, '}, status=status.HTTP_400_BAD_REQUEST)
        nav_data = NavigationInfo.objects.all()
        i=0
        for level in levels:
            if level in path.keys():
                i+=1
                if level == 'scope':
                    nav_data = nav_data.filter(scope__exact=path[level])
                elif level == 'level1':
                    nav_data = nav_data.filter(level1__exact=path[level])
                elif level == 'level2':
                    nav_data = nav_data.filter(level2__exact=path[level])
                elif level == 'level3':
                    nav_data = nav_data.filter(level3__exact=path[level])
                elif level == 'level4':
                    nav_data = nav_data.filter(level4__exact=path[level])
                elif level == 'level5':
                    nav_data = nav_data.filter(level5__exact=path[level])
                continue
            break
        #nav_data should now contain only those entries down the path specified in the request
        #Now find all unique levels below
        level_vals = list(nav_data.values(levels[i]).distinct())
        level_names = []
        for dict in level_vals:
            level_names.append(dict[levels[i]])

        if len(nav_data) > 1: #If there's more than one available path, no one id associated so leave as 0
            return JsonResponse({'subcategories':level_names, 'id':0}, status=status.HTTP_200_OK)
        elif len(nav_data) == 1: #If there's one available path, find id associated and return it
            nav_id = list(nav_data.values('id'))[0]['id']
            entry = FlatfileEntry.objects.get(navigation_info=nav_id)
            id = entry.ref_num
            return JsonResponse({'subcategories':level_names, 'id':id}, status=status.HTTP_200_OK)
        else: #If there are no paths, an error occurred in API call, return error message
            return JsonResponse({'message': 'Path not found'}, status=status.HTTP_404_NOT_FOUND)

@api_view(['POST'])
def item_calc(request):
    if request.method == 'POST':
        #Find entry of given id
        try:
            entry = FlatfileEntry.objects.filter(pk=request.data['id'])[0]
        except entry.DoesNotExist:
            return JsonResponse({}, status=status.HTTP_404_NOT_FOUND)
        except:
            return JsonResponse({}, status=status.HTTP_400_BAD_REQUEST)

        #Collect the right information
        source = entry.other_info.source
        unit = entry.calculation_info.cu
        factor = entry.calculation_info.ef

        #Calculate the total
        try:
            total = factor * request.data['amount']
        except:
            return JsonResponse({}, status=status.HTTP_400_BAD_REQUEST)

        return JsonResponse({"total":total, "calc_unit":unit, "source":source}, status=status.HTTP_200_OK)

webapp/views.py
from django.shortcuts import render
from django.http import HttpResponse
from webapp.forms import UserForm
from django.contrib.auth import authenticate, login
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout
from django.template import RequestContext
from django.shortcuts import redirect
from django.urls import reverse



def home(request):
    return render(request,'webapp/home.html')



def dbview(request):
    return render(request,'webapp/dbview.html')


def register(request):
    registered = False
    context = RequestContext(request)

    # If it's a HTTP POST, we're interested in processing form data.
    if request.method == 'POST':
        # Attempt to grab information from the raw form information.
        # Note that we make use of both UserForm and UserProfileForm.
        user_form = UserForm(request.POST)

        # If the two forms are valid...
        if user_form.is_valid():
            # Save the user's form data to the database.
            user = user_form.save()

            # Now we hash the password with the set_password method.
            # Once hashed, we can update the user object.
            user.set_password(user.password)
            user.save()


            # Update our variable to indicate that the template
            # registration was successful.
            registered = True
        else:
            # Invalid form or forms - mistakes or something else?
            # Print problems to the terminal.
            print(user_form.errors)
    else:
        # Not a HTTP POST, so we render our form using two ModelForm instances.
        # These forms will be blank, ready for user input.
        user_form = UserForm()


    # Render the template depending on the context.
    return render(request, 'webapp/register.html', context = {'user_form': user_form, 'registered': registered})
def user_login(request):
    context = RequestContext(request)

    # If the request is a HTTP POST, try to pull out the relevant information.
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            # Is the account active? It could have been disabled.
            if user.is_staff:
                # If the account is valid and active, we can log the user in.
                # We'll send the user back to the homepage.
                login(request, user)
                return redirect(reverse('webapp:home'))
            else:
                # An inactive account was used - no logging in!
                return HttpResponse("Your webapp account is disabled.")
        else:
            # Bad login details were provided. So we can't log the user in.
            print(f"Invalid login details: {username}, {password}")
            return HttpResponse("Invalid login details supplied.")

    # The request is not a HTTP POST, so display the login form.
    # This scenario would most likely be a HTTP GET.
    else:
        # No context variables to pass to the template system, hence the
        # blank dictionary object...
        return render(request, 'webapp/login.html')



@login_required
def user_logout(request):
    # Since we know the user is logged in, we can now just log them out.
    logout(request)
    # Take the user back to the homepage.
    return HttpResponseRedirect("/webapp/")

cs30_webapp/templates/webapp/dbview.html
{% extends 'webapp/base.html' %}
{% load static %}

{% block title_block %}
DBView
{% endblock %}

{% block navblock %}
<li class="breadcrumb-item"><a href="{% url 'webapp:home' %}">Home</a></li>
  {% if from == 'search' %}
    <li class="breadcrumb-item"><a href="{% url 'webapp:dbview' %}">DBView</a></li>
    <li class="breadcrumb-item active" aria-current="page">Search</li>
  {% else %}
    <li class="breadcrumb-item active" aria-current="page">DBView</li>
  {% endif %}
{% endblock %}


{% block body_block %}
<div class="row justify-content-end mb-2 sticky-top">
  <div class="col-md-auto site-colour-light py-2 px-2 rounded ">
    <a type="button" class="btn btn-primary" href="{% url 'webapp:add' %}"> Upload </a>
  </div>
</div>
<div style='display: grid; text-align: center; background-color: #E5EEE9'>
  <table>
    <tr>

      <th>Reference</th>
      <th>Scope</th>
      <th>Level 1</th>
      <th>Level 2</th>
      <th>Level 3</th>
      <th>Level 4</th>
      <th>Level 5</th>
      <th>EF</th>
      <th>CU</th>
      <th>Last updated</th>
      <th>Preference</th>
      <th>Source</th>

    </tr>

    {% for entry in entries %}
    <tr>
      <td>{{ entry.ref_num }}</td>
      <td>{{ entry.navigation_info.scope }}</td>
      <td>{{ entry.navigation_info.level1 }}</td>
      <td>{{ entry.navigation_info.level2 }}</td>
      <td>{{ entry.navigation_info.level3 }}</td>
      <td>{{ entry.navigation_info.level4 }}</td>
      <td>{{ entry.navigation_info.level5 }}</td>
      <td>{{ entry.calculation_info.ef }}</td>
      <td>{{ entry.calculation_info.cu }}</td>
      <td>{{ entry.other_info.last_update|date:"d/m/Y - g:i:s" }}</td>
      <td>{{ entry.other_info.preference }}</td>
      <td>{{ entry.other_info.source }}</td>
      <td><a type="button" class="btn btn-warning btn-sm" href="{% url 'webapp:edit' entry.ref_num  %}"> Edit </a></td>
      <td>
          <button type="button" class="btn btn-danger btn-sm" data-bs-toggle="modal" data-bs-target="#id{{ entry.ref_num  }}">
            Del
          </button>
          <!-- Modal for delete button to reduce/prevent accidental deletions.-->
          <div class="modal fade" id="id{{ entry.ref_num  }}" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title" id="staticBackdropLabel">Are you sure?</h5>
                  <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                  Deleting entry {{ entry.ref_num }} will remove it permanently.
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-success" data-bs-dismiss="modal">No thanks.</button>
                  <form id="delete" method="post" action="{% url 'webapp:delete' entry.ref_num %}">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-danger">Yes, I'm sure!</button>
                  </form>
                </div>
              </div>
            </div>
          </div>
      </td>
    </tr>
    {% endfor %}
  </table>
</div>
{% endblock %}

cs30_webapp/templates/webapp/edit.html
{% extends 'webapp/base.html' %}
{% load static %}

{% block title_block %}
EditDB - {{ entry.ref_num  }}
{% endblock %}

{% block headblock %}

{% endblock %}

{% block navblock %}
<li class="breadcrumb-item"><a href="{% url 'webapp:home' %}">Home</a></li>
<li class="breadcrumb-item"><a href="{% url 'webapp:dbview' %}">DBView</a></li>
<li class="breadcrumb-item active" aria-current="page">Edit</li>
{% endblock %}

{% block body_block %}

<div class="row justify-content-end mb-2 sticky-top">
  <div class="col-md-auto site-colour-light py-2 px-2 rounded ">
    <a type="button" class="btn btn-primary" href="{% url 'webapp:add' %}"> Upload </a>
  </div>
</div>

<form id="edit_form" method="post" action="{% url 'webapp:edit' entry.ref_num  %}">
  {% csrf_token %}
  <div class="mt-4" style='display: grid; text-align: center; background-color: #E5EEE9'>

    <h3> {{ entry.ref_num  }} </h3>

    {{ edit_form.errors }}

    <table>
      <tr>

        <th>Reference</th>
        <th>Scope</th>
        <th>Level 1</th>
        <th>Level 2</th>
        <th>Level 3</th>
        <th>Level 4</th>
        <th>Level 5</th>
        <th>EF</th>
        <th>CU</th>
        <th>Last updated</th>
        <th>Preference</th>
        <th>Source</th>

      </tr>

      <tr>
        <td><input type="number" id="ref_num" name="ref_num" class="form-control" maxlength="5" size="4" min="1" max="99999" value="{{ entry.ref_num }}" disabled></td>
        <td>
          <select id="scope" name="scope" class="form-control" selected="{{ entry.navigation_info.scope }}">
            <option {% if entry.navigation_info.scope  == "Scope 1" %} selected {% endif %} value="Scope 1">Scope 1</option>
            <option {% if entry.navigation_info.scope  == "Scope 2" %} selected {% endif %} value="Scope 2">Scope 2</option>
            <option {% if entry.navigation_info.scope  == "Scope 3" %} selected {% endif %} value="Scope 3">Scope 3</option>
            <option {% if entry.navigation_info.scope  == "Outside of Scopes" %} selected {% endif %} value="Outside of Scopes">Outside of Scopes</option>
          </select>
        </td>
        <td><input type="text" id="level1" name="level1" class="form-control" maxlength="30" size="10" value="{{ entry.navigation_info.level1 }}" disabled></td>
        <td><input type="text" id="level2" name="level2" maxlength="30" class="form-control" size="10" value="{{ entry.navigation_info.level2 }}" disabled></td>
        <td><input type="text" id="level3" name="level3" maxlength="30" class="form-control" size="10" value="{{ entry.navigation_info.level3 }}" disabled></td>
        <td><input type="text" id="level4" name="level4" maxlength="30" class="form-control" size="10" value="{{ entry.navigation_info.level4 }}" disabled></td>
        <td><input type="text" id="level5" name="level5" maxlength="30" class="form-control" size="10" value="{{ entry.navigation_info.level5 }}" disabled></td>
        <td><input type="text" id="ef" name="ef" class="form-control" maxlength="30" size="10" max="99999" min="0.000001" value="{{ entry.calculation_info.ef }}"></td>
        <td><input type="text" id="cu" name="cu" class="form-control" maxlength="30" size="6" value="{{ entry.calculation_info.cu }}"></td>
        <td><input type="text" id="last_update" class="form-control" name="last_update" size="10" value={{ entry.other_info.last_update|date:"d/m/Y - g:i:s" }} disabled></td>
        <td><input type="text" id="preference" class="form-control" name="preference" maxlength="1" size="3" min="1" max ="2" value="{{ entry.other_info.preference }}"></td>
        <td><input type="text" id="source" class="form-control" name="source" maxlength="9" size="7" value="{{ entry.other_info.source }}"></td>
        <td>
            <button type="button" class="btn btn-danger btn-sm" data-bs-toggle="modal" data-bs-target="#id{{ entry.ref_num  }}">
              Del
            </button>
        </td>
      </tr>
    </table>

  </div>

  <div class="mt-3 mx-3">
    <p>
      Last updated will automatically update upon saving.
    </p>
    {% for message in messages %}
      {{ message }}
    {% endfor %}
  </div>

  <div class="row justify-content-center mt-5">
    <div class="col-1 site-colour-light py-2 px-3 rounded site-text-dark text-center">
      <button type="submit" class="btn btn-primary" type="submit"><i class="bi bi-save2-fill"></i> Save </button>
    </div>
  </div>
</form>



<!-- Modal for delete button to reduce/prevent accidental deletions.-->
<div class="modal fade" id="id{{ entry.ref_num  }}" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="staticBackdropLabel">Are you sure?</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        Deleting entry {{ entry.ref_num }} will remove it permanently.
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-success" data-bs-dismiss="modal">No thanks.</button>
        <form id="delete" method="post" action="{% url 'webapp:delete' entry.ref_num %}">
          {% csrf_token %}
          <button type="submit" class="btn btn-danger">Yes, I'm sure!</button>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}

cs30_webapp/templates/webapp/home.html
{% extends 'webapp/base.html' %}
{% load static %}

{% block title_block %}
Home
{% endblock %}

{% block navblock %}
<li class="breadcrumb-item active" aria-current="page"><a href="{% url 'webapp:home' %}">Home</a></li>
{% endblock %}

{% block body_block %}

<div class="container">
  <div class="row justify-content-center">
    <div class="col-6">

      {% for message in messages %}
      {{ message }}
      {% endfor %}



        <div class="d-grid gap-2 col-12 mx-auto"">
          {% if user.is_authenticated %}

            {% if user.is_superuser %}
              <a class="btn button-menu" href="{% url 'admin:index' %}">Admin</a>
            {% endif %}

            <a class="btn button-menu" href="{% url 'webapp:dbview' %}">View DB</a>
            <a class="btn button-menu" href="{% url 'webapp:add' %}">Upload</a>
            <a class="btn button-menu" href="{% url 'webapp:logout' %}">Logout</a>

          {% else %}
              <a class="btn button-menu" href="{% url 'webapp:login' %}">Login</a>
              <a class="btn button-menu" href="{% url 'webapp:register' %}">Register</a>

          {% endif %}
        </div>
    </div>
  </div>
</div>

{% endblock %}

cs30_webapp/templates/webapp/login.html
{% extends 'webapp/base.html' %}
{% load static %}

{% block title_block %}
Login
{% endblock %}

{% block navblock %}
<li class="breadcrumb-item"><a href="{% url 'webapp:home' %}">Home</a></li>
<li class="breadcrumb-item active" aria-current="page">Login</li>
{% endblock %}

{% block body_block %}

<div class="row justify-content-center">
  <div class="col-4 site-colour-light pt-5 px-5 pb-2 rounded site-text-dark">
    <form id="login_form" method="post" action=".">
      {% csrf_token %}

      <label for="username" class="form-label mt-1">Username:</label>
      <input type="text" name="username" id="username" class="form-control" aria-describedby="username" required autofocus>

      <label for="password" class="form-label mt-1">Password:</label>
      <input type="password" name="password" id="password" class="form-control" aria-describedby="password" required>

      <div>

        {% for message in messages %}
          {{ message }}
        {% endfor %}

      </div>
      <button class="btn btn-primary my-3" type="submit"> Login </button>
    </form>

    <div>
      <p>
        Dont have an account? <a href="{% url 'webapp:register' %}"> Register </a>
      </p>
    </div>

  </div>
</div>
</div>
{% endblock %}