api/urls.py
from django.conf.urls import url
from api import views

urlpatterns = [
    url(r'^api/carbon$', views.entry_list),
    url(r'^api/carbon/(?P<pk>[0-9]+)$', views.entry_detail),
    url(r'^api/carbon/scope$', views.categories),
]

cs30_webapp/api/urls.py
from django.conf.urls import url
from api import views
app_name= 'api'

urlpatterns = [
    url(r'^api/carbon$', views.entry_list),
    url(r'^api/carbon/(?P<pk>[0-9]+)$', views.entry_detail),
    url(r'^api/carbon/scope$', views.categories),
    url(r'^api/carbon/info$', views.item_calc),
    url(r'^api/home$', views.home, name='home'),
    url(r'^api/carbon/search/(?P<query>[0-9a-zA-Z .!?*\\-]+)$', views.search),
]

cs30_webapp/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from webapp import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.home, name='home'),
    path('webapp/', include('webapp.urls')),
    path('admin/', admin.site.urls),
    path('register/', views.register, name='register'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout')
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

cs30_webapp/webapp/urls.py
from django.urls import path
from webapp import views
app_name = 'webapp'

urlpatterns = [
    path('', views.home, name='home'),
    path('dbview/', views.dbview, name='dbview'),
    path('register/', views.register, name='register'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('edit/<refnum>', views.edit, name='edit'),
    path('delete/<refnum>', views.delete, name='delete'),
    path('add/', views.add, name='add'),
    path('viewdb/', views.search, name='search'),
]

cs30_webapp/webapp/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.user.username

cs30_webapp/webapp/forms.py
from django import forms
from django.contrib.auth.models import User


SCOPE_CHOICES = (("Scope 1", "Scope 1"),
                 ("Scope 2", "Scope 2"),
                 ("Scope 3", "Scope 3"),
                 ("Outside of Scopes", "Outside of Scopes")
                 )

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    def __init__(self, *args, **kwargs):
        super(UserForm, self).__init__(*args, **kwargs)

        for fieldname in ['username']:
            self.fields[fieldname].help_text = None
    class Meta:
        model = User
        fields = ('username', 'email', 'password',)


class EditForm(forms.Form):
    scope = forms.ChoiceField(choices = SCOPE_CHOICES)
    level1 = forms.CharField(max_length = 30, min_length = 1, required=False)
    level2 = forms.CharField(max_length = 30, min_length = 1, required=False)
    level3 = forms.CharField(max_length = 30, min_length = 1, required=False)
    level4 = forms.CharField(max_length = 30, min_length = 1, required=False)
    level5 = forms.CharField(max_length = 30, min_length = 1, required=False)
    ef = forms.FloatField(max_value = 99999, min_value = 0.000001)
    cu = forms.CharField(max_length = 30)
    preference =  forms.IntegerField(min_value = 0, max_value=2)
    source = forms.CharField(max_length = 30)

class UploadForm(forms.Form):
    ref_num = forms.IntegerField(min_value = 0, max_value = 99999)
    scope = forms.ChoiceField(choices = SCOPE_CHOICES)
    level1 = forms.CharField(max_length = 30, min_length = 1)
    level2 = forms.CharField(max_length = 30, min_length = 1, required=False)
    level3 = forms.CharField(max_length = 30, min_length = 1, required=False)
    level4 = forms.CharField(max_length = 30, min_length = 1, required=False)
    level5 = forms.CharField(max_length = 30, min_length = 1, required=False)
    ef = forms.FloatField(max_value = 99999, min_value = 0)
    cu = forms.CharField(max_length = 30)
    preference =  forms.IntegerField(min_value = 0, max_value=2)
    source = forms.CharField(max_length = 30)

api/views.py
from django.shortcuts import render
from django.http.response import JsonResponse
from django.http import HttpRequest
from rest_framework.parsers import JSONParser
from rest_framework import status
from rest_framework.decorators import api_view
from api.models import FlatfileEntry, NavigationInfo, CalculationInfo, OtherInfo
from api.serializers import ApiSerializer, NavigationSerializer

@api_view(['GET','POST','DELETE'])
def entry_list(request):
    #GET list of entries, POST new entry, DELETE all entries
    if request.method == 'GET': #Retreive all entries or find entries by title
        entries = FlatfileEntry.objects.all()
        
        ref_num = request.GET.get('ref_num', None)
        if ref_num is not None:
            entries = entries.filter(ref_num__icontains=ref_num)
            
        api_serializer = ApiSerializer(entries, many=True)
        return JsonResponse(api_serializer.data, safe=False)
    elif request.method == 'POST': #Create and save new entry
        entry_data = request.data

        api_serializer = ApiSerializer(data=entry_data)
        if api_serializer.is_valid():
            api_serializer.save()
            return JsonResponse(api_serializer.data, status=status.HTTP_201_CREATED)
        return JsonResponse(api_serializer.errors, status=status.HTTP_400_BAD_REQUEST)
    elif request.method == 'DELETE': #Delete all entries - likely not needed in final implementation
        count = FlatfileEntry.objects.all().delete()
        #delete artifacts from nav, calc and other info
        NavigationInfo.objects.all().delete()
        CalculationInfo.objects.all().delete()
        OtherInfo.objects.all().delete()
        return JsonResponse({'message': '{} entires were deleted'.format(count[0])}, status=status.HTTP_204_NO_CONTENT)
    
    
@api_view(['GET','PUT','DELETE'])
def entry_detail(request, pk):
    #find entry by id
    try:
        entry = FlatfileEntry.objects.get(pk=pk)
    except entry.DoesNotExist:
        return JsonResponse({'message': 'Entry not found'})
        
    #GET / PUT / DELETE entry
    if request.method == 'GET': #Gets entry by specified id
        api_serializer = ApiSerializer(entry)
        return JsonResponse(api_serializer.data)
    elif request.method == 'PUT': #Update an existing entry
        entry_data = request.data
        api_serializer = ApiSerializer(entry, data=entry_data)
        if api_serializer.is_valid():
            api_serializer.save()
            return JsonResponse(api_serializer.data)
        return JsonResponse(api_serializer.errors, status=status.HTTP_400_BAD_REQUEST)
    elif request.method == 'DELETE': #Deletes entry by id
        entry.delete()
        return JsonResponse({'message': 'Entry was deleted'}, status=status.HTTP_204_NO_CONTENT)
        
@api_view(['GET','POST'])
def categories(request):
    if request.method == 'GET': #Complete
        #Return a list of scopes
        dict_scope_list = list(NavigationInfo.objects.all().values('scope').distinct())
        scopes = []
        for dict in dict_scope_list:
            scopes.append(dict['scope'])
        return JsonResponse({'message':scopes})
    if request.method == 'POST':
        #Return list of possible levels
        path = request.data
        levels = ['scope','level1','level2','level3','level4','level5']
        nav_data = NavigationInfo.objects.all()
        i=0
        for level in levels:
            if level in path.keys():
                i+=1
                if level == 'scope':
                    nav_data.filter(scope__icontains=path[level])
                elif level == 'level1':
                    nav_data.filter(level1__icontains=path[level])
                elif level == 'level2':
                    nav_data.filter(level2__icontains=path[level])
                elif level == 'level3':
                    nav_data.filter(level3__icontains=path[level])
                elif level == 'level4':
                    nav_data.filter(level4__icontains=path[level])
                elif level == 'level5':
                    nav_data.filter(level5__icontains=path[level])
                continue
            break
        #nav_data should now contain only those entries down the path specified in the request
        #Now find all unique levels below
        level_vals = list(nav_data.values(levels[i]).distinct())
        return JsonResponse({'message':level_vals})

cs30_webapp/api/views.py
from django.shortcuts import render
from django.http.response import JsonResponse
from django.http import HttpRequest
from django.db.models import Q
from rest_framework.parsers import JSONParser
from rest_framework import status, generics, filters
from rest_framework.decorators import api_view
from api.models import FlatfileEntry, NavigationInfo, CalculationInfo, OtherInfo
from api.serializers import ApiSerializer, NavigationSerializer, SearchSerializer
import json

def home(request):
    return render(request, 'api/home.html')

@api_view(['GET'])
def search(request, query):
    if request.method == 'GET':
        queryString = query
        try:
            #Int has been passed, check ref_num - NOTE: some issue with search, so an integer search does not function currently
            queryInt = int(queryString)
            entries = FlatfileEntry.objects.filter(Q(ref_num__icontains=queryInt))
            api_serializer = ApiSerializer(entries, many=True)
            return JsonResponse(api_serializer.data, safe=False, status=status.HTTP_200_OK)
        except ValueError:
            #Non int, check text fields
            entries = FlatfileEntry.objects.filter(Q(navigation_info__scope__icontains=queryString) | Q(navigation_info__level1__icontains=queryString) | Q(navigation_info__level2__icontains=queryString) | Q(navigation_info__level3__icontains=queryString) | Q(navigation_info__level4__icontains=queryString) | Q(navigation_info__level5__icontains=queryString) | Q(calculation_info__cu__icontains=queryString) | Q(other_info__source__icontains=queryString))
            api_serializer = ApiSerializer(entries, many=True)
            return JsonResponse(api_serializer.data, safe=False, status=status.HTTP_200_OK)
        except:
            return JsonResponse({}, status=status.HTTP_400_BAD_REQUEST)
    else:
        return JSONResponse({}, status=status.HTTP_400_BAD_REQUEST)

@api_view(['GET','POST','DELETE'])
def entry_list(request):
    #GET list of entries, POST new entry, DELETE all entries
    if request.method == 'GET': #Retreive all entries or find entries by ref_number
        entries = FlatfileEntry.objects.all()

        ref_num = request.GET.get('ref_num', None)
        if ref_num is not None:
            entries = entries.filter(ref_num__icontains=ref_num)

        api_serializer = ApiSerializer(entries, many=True)
        return JsonResponse(api_serializer.data, safe=False, status=status.HTTP_200_OK)
    elif request.method == 'POST': #Create and save new entry
        '''
        NOTE: This is a security issue - there is no restriction one who can input data, allowing
        for malicious actors to tamper with the database
        '''
        entry_data = request.data
        if 'payload' in entry_data.keys():
            entry_data = json.loads(entry_data['payload'])

        #Check if ref num in db, if so, reject, else, serializers
        refNum = entry_data['ref_num']
        print(refNum)
        try:
            e = FlatfileEntry.objects.get(pk=refNum)
            print(e)
            if e != None:
                return JsonResponse({}, status=status.HTTP_409_CONFLICT)
        except:
            pass

        api_serializer = ApiSerializer(data=entry_data)
        if api_serializer.is_valid():
            api_serializer.save()
            return JsonResponse({}, status=status.HTTP_201_CREATED)
        return JsonResponse(api_serializer.errors, status=status.HTTP_400_BAD_REQUEST)
    elif request.method == 'DELETE': #Delete all entries - likely not needed in final implementation
        '''
        NOTE: this is a security issue - the is no restriction on who can send this delete request
        '''
        count = FlatfileEntry.objects.all().delete()
        #delete artifacts from nav, calc and other info
        NavigationInfo.objects.all().delete()
        CalculationInfo.objects.all().delete()
        OtherInfo.objects.all().delete()
        return JsonResponse({'message': '{} entires were deleted'.format(count[0])}, status=status.HTTP_200_OK)


@api_view(['GET','PUT','DELETE'])
def entry_detail(request, pk):
    #find entry by id
    entry = FlatfileEntry
    try:
        entry = FlatfileEntry.objects.get(pk=pk)
    except entry.DoesNotExist:
        return JsonResponse({}, status=status.HTTP_404_NOT_FOUND)
    except:
        return JsonResponse({}, status=status.HTTP_400_BAD_REQUEST)

    #GET / PUT / DELETE entry
    if request.method == 'GET': #Gets entry by specified id
        api_serializer = ApiSerializer(entry)
        return JsonResponse(api_serializer.data, status=status.HTTP_200_OK)
    elif request.method == 'PUT': #Update an existing entry
        '''
        NOTE: this is a security issue - the is no restriction on who can send this update request,
        allowing for malicious actors to tamper with data
        '''
        entry_data = request.data
        if 'payload' in entry_data.keys():
            entry_data = json.loads(entry_data['payload'])

        api_serializer = ApiSerializer(entry, data=entry_data)
        if api_serializer.is_valid():
            api_serializer.save()
            return JsonResponse({}, status=status.HTTP_200_OK)
        return JsonResponse(api_serializer.errors, status=status.HTTP_400_BAD_REQUEST)
    elif request.method == 'DELETE': #Deletes entry by id
        '''
        NOTE: this is a security issue - the is no restriction on who can send this delete request
        '''
        entry.delete()
        return JsonResponse({}, status=status.HTTP_200_OK)

@api_view(['GET','POST'])
def categories(request):
    if request.method == 'GET': #Complete
        #Return a list of scopes
        dict_scope_list = list(NavigationInfo.objects.all().values('scope').distinct())
        scopes = []
        for dict in dict_scope_list:
            scopes.append(dict['scope'])
        return JsonResponse({'message':scopes}, status=status.HTTP_200_OK)
    if request.method == 'POST':
        #Return list of possible levels
        path = request.data
        levels = ['scope','level1','level2','level3','level4','level5']
        for p in path.keys():
            if p not in levels:
                return JsonResponse({'message':'Malformed request, '}, status=status.HTTP_400_BAD_REQUEST)
        nav_data = NavigationInfo.objects.all()
        i=0
        for level in levels:
            if level in path.keys():
                i+=1
                if level == 'scope':
                    nav_data = nav_data.filter(scope__exact=path[level])
                elif level == 'level1':
                    nav_data = nav_data.filter(level1__exact=path[level])
                elif level == 'level2':
                    nav_data = nav_data.filter(level2__exact=path[level])
                elif level == 'level3':
                    nav_data = nav_data.filter(level3__exact=path[level])
                elif level == 'level4':
                    nav_data = nav_data.filter(level4__exact=path[level])
                elif level == 'level5':
                    nav_data = nav_data.filter(level5__exact=path[level])
                continue
            break
        #nav_data should now contain only those entries down the path specified in the request
        #Now find all unique levels below
        level_vals = list(nav_data.values(levels[i]).distinct())
        level_names = []
        for dict in level_vals:
            level_names.append(dict[levels[i]])

        if len(nav_data) > 1: #If there's more than one available path, no one id associated so leave as 0
            return JsonResponse({'subcategories':level_names, 'id':0}, status=status.HTTP_200_OK)
        elif len(nav_data) == 1: #If there's one available path, find id associated and return it
            nav_id = list(nav_data.values('id'))[0]['id']
            entry = FlatfileEntry.objects.get(navigation_info=nav_id)
            id = entry.ref_num
            return JsonResponse({'subcategories':level_names, 'id':id}, status=status.HTTP_200_OK)
        else: #If there are no paths, an error occurred in API call, return error message
            return JsonResponse({'message': 'Path not found'}, status=status.HTTP_404_NOT_FOUND)

@api_view(['POST'])
def item_calc(request):
    if request.method == 'POST':
        #Find entry of given id
        try:
            entry = FlatfileEntry.objects.filter(pk=request.data['id'])[0]
        except entry.DoesNotExist:
            return JsonResponse({}, status=status.HTTP_404_NOT_FOUND)
        except:
            return JsonResponse({}, status=status.HTTP_400_BAD_REQUEST)

        #Collect the right information
        source = entry.other_info.source
        unit = entry.calculation_info.cu
        factor = entry.calculation_info.ef

        #Calculate the total
        try:
            total = factor * request.data['amount']
        except:
            return JsonResponse({}, status=status.HTTP_400_BAD_REQUEST)

        return JsonResponse({"total":total, "calc_unit":unit, "source":source}, status=status.HTTP_200_OK)

cs30_webapp/templates/api/home.html
{% extends 'webapp/base.html' %}
{% load static %}

{% block title_block %}
Home
{% endblock %}

{% block navblock %}
<li class="breadcrumb-item active" aria-current="page"><a href="{% url 'webapp:home' %}">Home</a></li>
{% endblock %}

{% block body_block %}

<div class="container">
  <div class="row justify-content-center">
    <div class="col-6">

      {% for message in messages %}
      {{ message }}
      {% endfor %}



        <div class="d-grid gap-2 col-12 mx-auto">
		
          {% if user.is_authenticated %}
			<p>This is the home page for the Carbon Footprint webapp's API. Here you will find instructions for use of the different endpoints.</p>
			<p>This is intended mainly for developers intending to understand the API, for purposes of alteration or expansion of this suite. This information is also available on the readme.md in the api app directory</p>
			<p><b>IMPORTANT NOTE: The API is not secured by authorisation, leaving data at risk, unfortunately we didn't have time to fix this problem so for now it's security by obscurity</b></p>
			
			<h3>API Endpoints</h3>
			<h4>General</h4>
			<ul>
			 <li>
			  <p>/api/carbon/(reference number) (GET)</p>
			  <div>
				<p>No parameters needed</p>
				<p>Returns specified entry as JSON document in flatfile form</p>
			  </div>
			 </li>
			</ul>
			<h4>Internal - ie used within dbms webapp</h4>
			<ul>
			 <li> 
			  <p>/api/carbon (GET)</p>
			  <div>
				<p>No parameters needed</p>
				<p>Returns all entries as a list of JSON documents in flatfile form</p>
			  </div>
			 </li>
			 <li>
			  <p>/api/carbon (POST)</p>
			  <div>
				<p>Parameters as defined in Flatfile form</p>
				<p>Adds new file to database, returning HTTP response to indicate outcome</p>
			  </div>
			 </li>
			 <li>
			  <p>/api/carbon (DELETE)</p>
			  <div>
				<p>No parameteres needed</p>
				<p>Deletes all files in the database - this is a development tool and should be removed as it is a security risk</p>
			  </div>
			 </li>
			 <li>
			  <p>/api/carbon/(reference number) (PUT)</p>
			  <div>
				<p>Parameters as defined in flatfile form</p>
				<p>Updates specified entry with new information</p>
			  </div>
			 </li>
			 <li>
			  <p>/api/carbon/(reference number) (DELETE)</p>
			  <div>
				<p>No parameters needed</p>
				<p>Deletes specified entry, returning an HTTP response to indicate outcome</p>
			  </div>
			 </li>
			</ul>
			<h4>External - ie used by visualisation app</h4>
			<ul>
			 <li>
			  <p>/api/carbon/scope (GET)</p>
			  <div>
				<p>No parameters needed</p>
				<p>Will return all scopes used by entries - that is, all the unique values of highest level of navigation information</p>
			  </div>
			 </li>
			 <li>
			  <p>/api/carbon/scope (POST)</p>
			  <div>
				<ul>
				 <li>Scope</li>
				 <li>Level 1</li>
				 <li>Level 2</li>
				 <li>Level 3</li>
				 <li>Level 4</li>
				</ul>
				<p>This will return all the values for the highest level non-specified path - eg, if both scope and level 1 was specified, then it would return the currently in use level 2 values for that given path</p>
				<p>The values will be returned as a list with name subcategories</p>
				<p>Should there only be one item on the path specified, the reference number of that item will also be returned as ref_num</p>
			  </div>
			 </li>
			 <li>
			  <p>api/carbon/info</p>
			  <div>
			    <ul>
				 <li>Reference number of item</li>
				 <li>Amount to be calculated</li>
				<ul>
				<p>Used to calculate how much carbon a certain amount of an item generates, will return the number as result, the unit associated as calc_unit and the source of the information as source</p>
			  </div>
			 </li>
			</ul>
			<h4>Flatfile form</h4>
			<p>This refers to the form the data is stored in the database, and looks like the following</p>
			<ul>
			 <li>ref_num</li>
			 <li>navigation_info</li>
			 <ul>
			  <li>scope</li>
			  <li>level_1</li>
			  <li>level_2</li>
			  <li>level_3</li>
			  <li>level_4</li>
			  <li>level_5</li>
			 </ul>
			 <li>calculation_info</li>
			 <ul>
		      <li>ef (emmissions factor)</li>
			  <li>cu (calculation unit)</li>
			 </ul>
			 <li>other_info</li>
			 <ul>
			  <li>last_update</li>
		      <li>preference</li>
		      <li>source</li>
		     </ul>
		    </ul>
		  {% else %}
			<p>Sorry, but you must be logged in to view this for now! For security purposes</p>
		    <!-- To remove this authentication, just get rid of the if block this is enclosed in -->
		  {% endif %}
        </div>
    </div>
  </div>
</div>

{% endblock %}